### ISSUE TITLE
Test fails: PageNotFound

### ISSUE THREAD

**Issue by marielvanstav** [OrganicIrradiation/ratebeer#52]
I installed ratebeer on my Mac using python 2.7 by running: 

```virtualenv testA```
```source testA/bin/activate```
```pip install git+https://github.com/alilja/ratebeer.git```
```wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py```

Running ```python test.py``` returns: 

```
======================================================================
ERROR: test_beer (__main__.TestBeer)
Make sure the results for a beer contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 20, in test_beer
    results = RateBeer().beer('/beer/new-belgium-tour-de-fall/279122/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/new-belgium-tour-de-fall/279122/

======================================================================
ERROR: test_beer_aliased (__main__.TestBeer)
Check that AliasedBeer exception is raised properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 111, in test_beer_aliased
    self.assertRaises(rb_exceptions.AliasedBeer, rb.beer, "/beer/new-belgium-biere-de-mars/113241/")
  File "/Users/mariel/anaconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/new-belgium-biere-de-mars/113241/

======================================================================
ERROR: test_beer_closed_brewery (__main__.TestBeer)
Handling beers from closed brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 42, in test_beer_closed_brewery
    results = RateBeer().beer('/beer/hantens-hildener-landbrau/140207/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/hantens-hildener-landbrau/140207/

======================================================================
ERROR: test_beer_closed_contract_brewery (__main__.TestBeer)
Handling beers from closed contract brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 47, in test_beer_closed_contract_brewery
    results = RateBeer().beer('/beer/crew-republic-x-11-wet-hop/298026/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/crew-republic-x-11-wet-hop/298026/

======================================================================
ERROR: test_beer_contract_brewed (__main__.TestBeer)
Handling contract brewed beers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 53, in test_beer_contract_brewed
    results = RateBeer().beer('/beer/benediktiner-weissbier/157144/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/benediktiner-weissbier/157144/

======================================================================
ERROR: test_beer_get_reviews (__main__.TestBeer)
Check to make multi-page review searches work properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 61, in test_beer_get_reviews
    self.assertIsNotNone(next(reviews))
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 213, in get_reviews
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/deschutes-inversion-ipa/55610/

======================================================================
ERROR: test_beer_no_abv (__main__.TestBeer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 70, in test_beer_no_abv
    results = RateBeer().beer('/beer/deschutes-altitude-amber/92102/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/deschutes-altitude-amber/92102/

======================================================================
ERROR: test_beer_no_ratings (__main__.TestBeer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 84, in test_beer_no_ratings
    results = RateBeer().beer('/beer/deschutes-abyssident/194792/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/deschutes-abyssident/194792/

======================================================================
ERROR: test_beer_retired_beer (__main__.TestBeer)
Attributes for retired beers display properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 105, in test_beer_retired_beer
    results = RateBeer().beer('/beer/shorts-funkin-punkin/79468/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/shorts-funkin-punkin/79468/

======================================================================
ERROR: test_beer_unicode (__main__.TestBeer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 97, in test_beer_unicode
    results = RateBeer().beer('/beer/stedji-oktoberbjor/292390/')
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 136, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 132, in get_beer
    return models.Beer(url, fetch)
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/models.py", line 112, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /beer/stedji-oktoberbjor/292390/

======================================================================
ERROR: test_str_nonascii_search (__main__.TestSearch)
Test out the search function with a str with more than ASCII characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 184, in test_str_nonascii_search
    results = RateBeer().search("to øl jule mælk")
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 120, in search
    url = '/beer/{0}/{1}/'.format(beer_data['name'].replace(' ', '-').lower(), beer_data['id'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 3: ordinal not in range(128)

======================================================================
ERROR: test_unicode_nonascii_search (__main__.TestSearch)
Test out the search function with a unicode string with more than ASCII characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 202, in test_unicode_nonascii_search
    results = RateBeer().search(u"to øl jule mælk")
  File "/Users/mariel/testA/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 120, in search
    url = '/beer/{0}/{1}/'.format(beer_data['name'].replace(' ', '-').lower(), beer_data['id'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 3: ordinal not in range(128)

======================================================================
FAIL: test_fetch_by_letter (__main__.TestAlpha)
Make sure the results for a brewery list by index contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 216, in test_fetch_by_letter
    self.assertTrue(beer.url == u'/brewers/a-duus-and-co/1668/')
AssertionError: False is not true

----------------------------------------------------------------------
Ran 24 tests in 9.073s

FAILED (failures=1, errors=12)
```

Any ideas on how to fix this?

**Comment by parryc** [comment]
@marielvanstav, it's been a little slow around here to merge in the necessary changes, but you can pull from my fork and it should fix most things https://github.com/OrganicIrradiation/ratebeer/issues/51. Searching and getting beer information, at least works. I haven't had the time recently to go in and fix some of the ancillary API calls. Let me know if you have any issues.

**Comment by jciupis** [comment]
@parryc Hi, have you had any progress? I'm trying to use the version you mentioned in the comment, but the functionalities are still limited - I'm having problems getting review and brewery code to work. My main goal was to get the `get_reviews` code running, do you have any idea how I could fix it?

**Comment by parryc** [comment]
Hi @jciupis, sorry, no update from me – brewery and reviews are unfortunately not needed for my specific uses, so I haven't been compelled to update my fork to the newest API (as frustrating as it may sound for you. 

It appears from a very quick look, that the API call for review information is some combination of the two operations below. Using [this beer](https://www.ratebeer.com/beer/utepils-ewald-the-golden/484278) as an example.

`[{"operationName":"beerReviews","variables":{"beerId":"484278"},"query":"query beerReviews($beerId: ID!) {\n  beerReviews(beerId: $beerId, order: TOP_RATERS, first: 5) {\n    reviews: items {\n      score\n      comment\n      createdAt\n      author {\n        username\n        city\n        state {\n          name\n          __typename\n        }\n        country {\n          name\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"},{"operationName":"tagDisplay","variables":{"beerId":"484278"},"query":"query tagDisplay($beerId: ID!, $first: Int) {\n  tagDisplayArr: beerTags(beerId: $beerId, first: $first) {\n    items {\n      id\n      urlName: plain\n      __typename\n    }\n    __typename\n  }\n}\n"},{"operationName":"beerReviews","variables":{"beerId":"484278","order":"RECENT","first":7},"query":"query beerReviews($beerId: ID!, $authorId: ID, $order: ReviewOrder, $after: ID) {\n  beerReviewsArr: beerReviews(beerId: $beerId, authorId: $authorId, order: $order, after: $after) {\n    items {\n      ...ReviewItem\n      __typename\n    }\n    totalCount\n    last\n    __typename\n  }\n}\n\nfragment ReviewItem on Review {\n  id\n  comment\n  score\n  scores {\n    appearance\n    aroma\n    flavor\n    mouthfeel\n    overall\n    __typename\n  }\n  author {\n    id\n    username\n    reviewCount\n    __typename\n  }\n  checkin {\n    id\n    place {\n      id\n      name\n      city\n      state {\n        id\n        name\n        __typename\n      }\n      country {\n        id\n        name\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  servedIn\n  likeCount\n  likedByMe\n  createdAt\n  updatedAt\n  __typename\n}\n"}]`

There does not appear to be an API call to scrape Brewery information, so those information will have to be old school scraped from the web site, following the code in `Brewery._populate`.  Given the renewed interest (2 people in a month!) I will try to fix the rest of the code sooner rather than later. Please post again if you have any questions or if you are able to update the Review and Brewery code. Feel free to fork the fork above and we can merge everything in together, back into this main repo.

**Comment by jciupis** [comment]
@parryc Actually, I managed to get text of reviews with the snippet you provided. As I need the data for an academic machine learning project, that was basically my goal. Thank you very much for your help!

I have close to no experience in web stuff, so I don't think I would be much help with fixing the whole thing properly. You can consider my issue closed though :)

**Comment by parryc** [comment]
Great, best of luck @jciupis. Closing issue.
